name: Scheduled Task

on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run bash script
        run: |
          chmod +x ./prevent_server_spin_down.sh
          ./prevent_server_spin_down.sh
